# Generated by Django 5.1.7 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
